import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { getProducts } from './api/modules/product';
import { NavBar } from '@/components/NavBar/NavBar';
import { Footer } from '@/components/Footer/Footer';
import { ProductsContextProvider } from '@/store/product-context-provider';
import { CartContextProvider } from '@/store/cart-context-provider';
import '../styles/globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// fetching products data (in server-component on the root)
	const productsPromise = getProducts();

	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable}`}
				suppressHydrationWarning>
				{/* pass fetched data to ContextProvider (state management solution) so it can be used in the entire app */}
				<ProductsContextProvider productsPromise={productsPromise}>
					<CartContextProvider>
						<NavBar />
						<main>{children}</main>
						<Footer />
					</CartContextProvider>
				</ProductsContextProvider>
			</body>
		</html>
	);
}
