// TODO: Add hero banner
// TODO: Add carousel
// TODO: Make layout wrapper for all pages (1400px, 48px margin-top, background: white ...)
// TODO: Find out how to share variables between CSS modules

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { getProducts } from './api/modules/product';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';
import { ProductsContextProvider } from '@/store/product-context-provider';
import { CartContextProvider } from '@/store/cart-context-provider';
import classes from './layout.module.css';
import '../styles/globals.css';
import { ToastContainer } from 'react-toastify';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// fetching products data (in server-component on the root)
	const productsPromise = getProducts();

	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable}`}
				suppressHydrationWarning>
				{/* pass fetched data to ContextProvider (state management solution) so it can be used in the entire app */}
				<ProductsContextProvider productsPromise={productsPromise}>
					<CartContextProvider>
						<ToastContainer />
						<Header />
						<main className={classes.main}>{children}</main>
						<Footer />
					</CartContextProvider>
				</ProductsContextProvider>
			</body>
		</html>
	);
}
